### ISSUE TITLE
OpenBSD 5.7 / LibreSSL

### ISSUE THREAD

**Issue by rvalles** [janvidar/uhub#32]
Built 0.5.0 on OpenBSD 5.7 and then, after experiencing this issue, built current git. No dice.

Couldn't make it work with LibreSSL, with config files and certificate identical to those used on a Linux server.

Server runs but clients can't connect.

Clientside (eiskalt) error looks like: Fail: SSL Error: error:00000001:lib(0):func(0):reason(1) (0, 1).

With TLS disabled, clients can connect just fine. But of course that's not ok in the present world.

**Comment by janvidar** [comment]
Hi,

I haven't tested OpenBSD 5.7 with LibreSSL for a while, but in general the usual problem is that uhub has a strong default TLS setting which often is not compatible with various clients which expect a much older TLS configuration.

The default cipher suite and TLS requirement is:
tls_ciphersuite = "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
tls_version = "1.2"

This does not work with many different clients, so you can try reducing the security config slightly:

tls_ciphersuite = "HIGH:!aNULL:!eNULL"
tls_version = "1.0"

Let me know if this works, or not.

**Comment by rvalles** [comment]
Hi,

Yes, it made things work. The key setting is TLS 1.0 (1.1 wouldn't work). What I was missing here is that my old server was some 0.4.1-ish build from git, so things probably changed in between.

tls_ciphersuite = "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:
RSA+3DES:!aNULL:!MD5:!DSS"
tls_version = "1.0"

Does work. When requiring TLS 1.1, it doesn't.

If I understand correctly, I can comment the ciphersuite line and the end result will be identical; it does indeed work without, but is that for certain?

I should also mention that if I launch it by hand rather than rc script (to see output), I see some errors, which you might want to investigate:

# sudo -u _uhub uhub
2015-05-31 14:19:42  ERROR: net_setsockopt, fd=5: Invalid argument (22)
2015-05-31 14:19:42  ERROR: net_socket_create(): Dual stack IPv6/IPv4 is not supported.
2015-05-31 14:19:42   INFO: Starting uhub/0.5.0, listening on 0.0.0.0:3747...
2015-05-31 14:19:42   INFO: Enabling TLS (LibreSSL 2.1), using certificate: /etc/uhub/my.crt, private key: /etc/uhub/my.key
2015-05-31 14:19:42   INFO: Loaded plugin: /usr/lib/uhub/mod_auth_sqlite.so: SQLite authentication plugin, version 1.0.
2015-05-31 14:19:42   INFO: Loaded plugin: /usr/lib/uhub/mod_logging.so: Logging plugin, version 1.0.
2015-05-31 14:19:42   INFO: Loaded plugin: /usr/lib/uhub/mod_welcome.so: Welcome plugin, version 0.1.
2015-05-31 14:19:42   INFO: Loaded plugin: /usr/lib/uhub/mod_chat_history.so: Chat history plugin, version 1.0.

Server has IPv6; it's somewhat sad it can't be used. My current (home) connection is a filthy DS Lite too, so people can't connect to me via IPv4.

Thanks you for the help.

Kind Regards,
Roc.

**Comment by janvidar** [comment]
If you have IPv6, you can configure your server_bind_addr to "::" to force it to IPv6.
By default it is set to the special value "any" which is mapped to "0.0.0.0" and "::", however this seems to work on Linux mostly.
