### ISSUE TITLE
Why in debian repository, not 0.5.0 version?

### ISSUE THREAD

**Issue by mcdemon05** [janvidar/uhub#33]

**Comment by janvidar** [comment]
Hi,

I don't maintain the Debian packages, but the 0.5.x branch is definitely being packaged. Which version of Debian are you using?

http://tehnick.github.io/uhub/

**Comment by mcdemon05** [comment]
i use 7.9 Debian

**Comment by mcdemon05** [comment]
sudo add-apt-repository -y 'deb http://ppa.launchpad.net/tehnick/tehnick/ubuntu precise main'

after:

root@adc-test:/home/maksimenko# sudo apt-get install -V uhub
Чтение списков пакетов… Готово
Построение дерева зависимостей
Чтение информации о состоянии… Готово
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 uhub : Зависит: libc6 (>= 2.15) но 2.13-38+deb7u8 будет установлен

**Comment by janvidar** [comment]
You should not use an ubuntu package on debian.
I suggest you ask Boris Pek, who is the maintainer of the debian and ubuntu packages. He can be reached by e-mail "tehnick AT debian DOT org".
