### ISSUE TITLE
Unable to create any user account.

### ISSUE THREAD

**Issue by HublistDotNet** [janvidar/uhub#51]
After initial successfull uHub install  ver. 0.5.1 this happened:

**motd.txt** was missing in etc/uhub - this caused uHub failure to start - i see this is issue already posted.
I did add motd.txt to that folder manually - and this resolved issue.
Users.conf doesn't exist - also reported here.
Then when trying to make an admin account via command line  - error **table users doesn't exist**.
How do i fix that?

**Comment by mimicmod** [comment]
Did you use uhub-passwd create command first?

**Comment by HublistDotNet** [comment]
uhub-passwd create add Username password admin
fails with message table users doesnt exits .

Either incorrect syntax , but thats what it tells me in help.
or I might be running it from wrong location  - will check that later and repost results.

**Comment by HublistDotNet** [comment]
Oh Jeez.
Ok i was not aware it needs directories too 

Yes it works like that.
Thanx!

**Comment by mimicmod** [comment]
No it is not created automatically during install. Sqlite only creates the file when you try to run any command on it. Deletion is not necessary, but more secure, since you do not know what exactly was created in the file while you were trying to create the database.

**Comment by HublistDotNet** [comment]
OK thanx.
That makes sense.
Now does uhub have regme command? For unregistered users so they can reg themselves?

**Comment by Kcchouette** [comment]
I don't know how to reg user, but it seems that this kind of command exists: https://github.com/janvidar/uhub/commit/998f5a57e24adedeedfefa9db611b517b2b76102

**Comment by mimicmod** [comment]
Official uhub probably does not have a register command since ACL was moved to plugins. My uhub branch is probably the only one fully managing accounts through hub commands. I send no pull requests, but feel free to use and revise anything from https://github.com/mimicmod/uhub/blob/master/src/plugins/mod_auth_sqlite.c.

**Comment by Kcchouette** [comment]
I think !register works. I'll test that in a few hours

Why don't you want to do a PR, @mimicmod

**Comment by Kcchouette** [comment]
> I think !register works. I'll test that in a few hours

My bad, it seems to not working… even using file_acl :(

**Comment by janvidar** [comment]
I think there is some work needed to hook things up correctly.
The plug-in interface has rudimentary support for it and `mod_auth_sqlite` seems to implement it. However, nothing is connected to call this plug-in API.

I think the solution is to register a command in the hub's core that maps to the `acl_register_user()` function, then this function will invoke the plug-in interface until the first plug-in returns `enum plugin_status st_allow`.

That being said - I'm not sure how much work is needed inside the actual plug-in to make sure it works correctly, safely or reliably.

**Comment by mimicmod** [comment]
Why I do not send any PR is a good question and I do not have a good answer to it. I just was not posting them from the beginning when I forked uhub and If I make a PR now 105 commits ahead of janvidar's uhub will have to be revised. I implemented several features like opchat (has its own branch here) etc. Some things were changed in the core for my plugins to work. If you really want I will click the PR button ;)

**Comment by janvidar** [comment]
I added a *completely* untested `!register` support for this on the acl/user_self_register_support branch:
https://github.com/janvidar/uhub/commit/e3852b7fade2a9c850ed02a75609dd1c33397239

**Comment by HublistDotNet** [comment]
i can give it a test drive but i dont know how do i download uhub with this branch included.Sorry im new to github.

**Comment by Kcchouette** [comment]
@HublistDotNet you can download the branch using this link: https://github.com/janvidar/uhub/archive/acl/user_self_register_support.zip

**Comment by HublistDotNet** [comment]
ok i downloaded installed but !register or !regme gives me this:
[21:00] <[Test Drive] uHub 0.5.1> *** regme: Command not found.
[21:00] <[Test Drive] uHub 0.5.1> *** register: Command not found.

If i had installed prev version of uHub do i need to uninstall it first maybe? Does make clean make make install overwrite all files?
Whatever the case  this:
https://github.com/janvidar/uhub/archive/acl/user_self_register_support.zip
Still has no !rrgister or !regme that works from mainchat.

**Comment by janvidar** [comment]
You must configure: register_self = on
This enables the !register command (not !regme).

**Comment by HublistDotNet** [comment]
in settings.xml before make ? Right?

**Comment by Kcchouette** [comment]
no, in /etc/uhub/uhub.conf
And before starting uhub

**Comment by HublistDotNet** [comment]
Yeah.
It works :)
DOes uHub have 1. redirect command?  2. Redirect host setting? For example redirect if min share not met - or min slots not met etc....

**Comment by HublistDotNet** [comment]
I see, redirect command should be on todo list (just my opinion).
Ok, thank you all for your help. I guess im gonna close this as most of this is a bit off topic and its my fault as i wasn't able to figure out some settings by myself.
Thanx again. Lets keep this hubsoft alive if possible.
