### ISSUE TITLE
Unable to clone repo in Windows due to SQLite remote link in thirdparty folder

### ISSUE THREAD

**Issue by CollinChaffin** [janvidar/uhub#58]
The new "de-improved" GH client for WIN is apparently unable to translate remote repo links such as what you have in the thirdparty folder which is a remote junction to your SQLite repo.  This makes it currently impossible (from everything I have tried) to simply clone the repo and keep it up to date, rather than manually downloading the master.zip.

If possible since it has not changed in almost a decade and is only a small handful of files, if you could possibly consider just moving those few SQLite files needed into the thirdparty folder it would greatly simplify things.  TIA!

**Comment by tehnick** [comment]
> if you could possibly consider just moving those few SQLite files needed into the thirdparty folder it would greatly simplify things.

This a very bad idea due to a number of reasons.
The best solution would be just remove this git submodule at all.
But for resolving of your problem it is enough just make a tiny change in file `.gitignore`:
```
[submodule "thirdparty/sqlite"]
	path = thirdparty/sqlite
	url = https://github.com/janvidar/sqlite.git
```
I'll prepare PR for this.
