### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by Kcchouette** [janvidar/uhub#67]
Uhub has 22 branches 21 are stalled, and **15** have more dev (see the number of commit in parentheses) than the master one:
 - libevent_work (4)
 - 0.2.x-stable (1)
 - history_on_login (1)
 - visual_studio_2010_work (11)
 - adc_client_adcs_support (12)
 - 0.3.x-stable (13)
 - dynamic_hub_commands (8)
 - command_cleanup (1)
 - gh-pages (1)
 - cmake (1)
 - link_support (2)
 - op_notify (8)
 - writev_support (3)
 - acl/user_self_register_support (3)
 - plugin_rework_2019-01 (2)

Maybe should you remove the **6** others, or are there reasons to keep them?

And maybe should you merge some ready-work of theses branches?

**Comment by janvidar** [comment]
Why?

**Comment by Kcchouette** [comment]
Spring cleaning  
More seriously, because we / I don't know which branch is a draft one, which one is in active development, which branch is not used anymore etc

**Comment by janvidar** [comment]
In git, branches are cheap. I create a new branch for everything I do (mostly).
You should generally only care about the master branch - which is the place where everything ends up eventually.
