### ISSUE TITLE
Limit user's reconnection time

### ISSUE THREAD

**Issue by Tantrix** [janvidar/uhub#72]
_[07.10.19] 00:45.29 ] *** Parts: andr1961
[07.10.19] 00:45.29 ] *** Joins: andr1961
[07.10.19] 00:46.18 ] *** Parts: trance[]maniac
[07.10.19] 00:46.18 ] *** Joins: trance[]maniac_

To avoid a too fast user's reconnection. It can be monitored by the IP address (and may probably be controlled by antiflood timer).

**Comment by janvidar** [comment]
I think this commit addresses the underlying issue here:

https://github.com/janvidar/uhub/commit/cff10910ad08237e2345627672716c97b8cda949

**Comment by Tantrix** [comment]
> 
> 
> I think this commit addresses the underlying issue here:
> 
> [cff1091](https://github.com/janvidar/uhub/commit/cff10910ad08237e2345627672716c97b8cda949)

Nice work on ghosts hunting! It really made a difference.

But, hey, a way to hammer the hub with Reconnect button stays here.

_[03.12.19] 18:47.49 ] *** Parts: andr1961
[03.12.19] 18:47.54 ] *** Joins: andr1961_

So that particular kind of protection is needed too.
